name: Project Management Automation

on:
  issues:
    types: [opened, closed, edited]
  pull_request:
    types: [opened, closed, merged]

jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add to Project
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/users/jeremyeder/projects/1
        github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
        
    - name: Update issue with outcome tracking
      if: github.event_name == 'issues' && github.event.action == 'opened'
      uses: actions/github-script@v7
      with:
        script: |
          const issueLabels = context.payload.issue.labels.map(label => label.name);
          
          if (issueLabels.includes('outcome')) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🎯 **Outcome Created** - This is a top-level business objective. Consider:\n\n- Success metrics and KPIs\n- Timeline and milestones\n- Required epics to achieve this outcome\n- Stakeholder alignment'
            });
          } else if (issueLabels.includes('epic')) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🚀 **Epic Created** - This is a major work item. Consider:\n\n- Which outcome this contributes to\n- Required stories to complete this epic\n- Dependencies and blockers\n- Resource requirements'
            });
          }